"""update models

Revision ID: 597d2f43d03c
Revises: 0003_submissoes_abertas_evt
Create Date: 2026-06-09 18:46:02.355074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '597d2f43d03c'
down_revision: Union[str, Sequence[str], None] = '0003_submissoes_abertas_evt'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_user_relations', sa.Column('tags', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=False))
    op.alter_column('event_user_relations', 'role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('ouvinte', 'pesquisador', 'revisor', 'organizador', name='event_relation_role', native_enum=False),
               existing_nullable=False)
    op.alter_column('event_user_relations', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('pendente', 'ativo', 'cancelado', 'rejeitado', name='event_relation_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ativo'::character varying"))
    op.alter_column('events', 'categoria',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('tecnologia', 'saúde', 'engenharia', 'educação', 'direito', name='event_category', native_enum=False),
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('inscrições abertas', 'inscrições encerradas', name='event_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.Enum('inscrições abertas', 'inscrições encerradas', name='event_status', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('events', 'categoria',
               existing_type=sa.Enum('tecnologia', 'saúde', 'engenharia', 'educação', 'direito', name='event_category', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('event_user_relations', 'status',
               existing_type=sa.Enum('pendente', 'ativo', 'cancelado', 'rejeitado', name='event_relation_status', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'ativo'::character varying"))
    op.alter_column('event_user_relations', 'role',
               existing_type=sa.Enum('ouvinte', 'pesquisador', 'revisor', 'organizador', name='event_relation_role', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('event_user_relations', 'tags')
    # ### end Alembic commands ###
